lesson2
Samoilenkoaa/Popular_Libraries pull request #2
Opened 2021-08-02 14:08 UTC by Samoilenkoaa

2021-08-03 04:31 UTC, PeterBukhal-Geekbrains requested changes
Есть критические замечания. Пока не принимаю.

2021-08-03 04:31 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/bignerdranch/android/popularlibraries/MainActivity.kt
> +    val navigator = AppNavigator(this, R.id.container)
Инкапсуляция нарушена, должно быть с модификатором `private`

2021-08-03 04:31 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/bignerdranch/android/popularlibraries/UsersPresenter.kt
> +            router.navigateTo(Detail(usersListPresenter.users[itemView.pos]))
:100:

2021-08-03 04:31 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/bignerdranch/android/popularlibraries/UsersPresenter.kt
> +class UsersPresenter(val usersRepo: GithubUsersRepo, val router: Router) : MvpPresenter<UsersView>() {
Инкапсуляция нарушена, должно быть с модификатором `private`

2021-08-03 04:31 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/bignerdranch/android/popularlibraries/UsersFragment.kt
> +    val presenter: UsersPresenter by moxyPresenter { UsersPresenter(GithubUsersRepo(), App.instance.router) }
Инкапсуляция нарушена, должно быть с модификатором `private`

2021-08-03 04:31 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/bignerdranch/android/popularlibraries/UsersFragment.kt
> +        fun newInstance() = UsersFragment()
При создании обьектов используя фабрики нужно возвращать максимально базовый тип в иерархии наследования если такая имеется, то есть делать восходящее преобразование. В данном случае к `Fragment`, см. `FragmentScreen` из Cicerone. Это дает больше возможностей по изменению реализации, и явно указывает на то что не следует использовать или ссылаться на тип конкретного фрагмента.

2021-08-03 04:31 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/bignerdranch/android/popularlibraries/UsersPresenter.kt
> +    object Screens {
У тебя уже есть `IScreens` как минимум можно сделать это там, но лучше вынести из этого класса в отдельный файл. **Напоминаю что мы не используем Android зависимости в коде презентеров. Это грубое нарушение MVP.** В фабрику нужно не `Bundle` передавать но все таки самого пользователя, и уже там добавлять в аргументы. Так ты скроешь подробность о том что есть `Bundle` и аргументы внутри фрагмента.

2021-08-05 14:02 UTC, PeterBukhal-sovcombank approved these changes
Отлично, задание выполнено, замечаний нет.

2021-08-05 14:02 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/bignerdranch/android/popularlibraries/ui/DetailUserFragment.kt
> +    private var _binding: FragmentUserDetailBinding? = null
Удобно использовать https://github.com/kirich1409/ViewBindingPropertyDelegate. См. последний пример с разбором ДЗ урока 2.

2021-08-07 13:41 UTC, merged